version: "3.3"
services:
  # server:
  #   container_name: server_container
  #   image: joshjacobbaker/backendexpressserverpostgres
  #   restart: always
  #   ports:
  #     - "8080:8080"
  db:
    container_name: pg_container
    image: postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
volumes:
  postgres-volume:
    external: true
